---
# author: fat

- block:
    - name: install_file | Check zabbix-agent bin file.
      stat: path={{ software_files_path }}/{{ zabbix_agent_file }}
      register: result_agent_file
      
    - name: install_file | Create software directory.
      file: path={{ software_files_path }} state=directory
      when: not result_agent_file.stat.exists
      run_once: true

    - name: install_file | Download zabbix-agent bin file.
      get_url: 
          url: "{{ zabbix_agent_file_url[zabbix_agent_file_version|string] }}"
          dest: "{{ software_files_path }}/{{ zabbix_agent_file }}" 
      when: not result_agent_file.stat.exists
  delegate_to: localhost

- name: install_file | Copy bin file to agent
  unarchive:
    src: "{{ software_files_path }}/{{ zabbix_agent_file }}"
    dest: "/tmp"
    creates: "/tmp/{{ zabbix_agent_file_path }}"

- name: install_file | Ensure old packages removed.
  apt: name=zabbix-agent  state=absent purge=yes
  when: ansible_distribution|lower == 'ubuntu'
  ignore_errors: true
  
- name: install_file | Ensure old packages removed.
  yum: name=zabbix-agent  state=absent      
  when: ansible_distribution|lower == 'centos'
  ignore_errors: true
  
- name: install_file | move bin files to directory
  copy: 
    src: "/tmp/{{ zabbix_agent_file_path }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: preserve
  with_items:
    - {src: 'bin/zabbix_get', dest: '/usr/bin'}
    - {src: 'bin/zabbix_sender', dest: '/usr/bin'} 
    - {src: 'sbin/zabbix_agentd', dest: '/usr/sbin'}

- name: configure | Add zabbix group.
  group: 
    name: "{{ zabbix_agent_group }}"
    state: present
    
- name: configure | Add zabbix user.
  user:
    name: "{{ zabbix_agent_user }}"
    comment: Zabbix User
    group: "{{ zabbix_agent_group }}"
    shell: /sbin/nologin

- name: install_file | Check zabbix-agent pid directory.
  stat: path={{ zabbix_agent_pid_path }}
  register: zabbix_pid_result  

- name: install_file | Create zabbix pid directory.
  file: path={{ zabbix_agent_pid_path }} state=directory owner={{ zabbix_agent_user }} group={{ zabbix_agent_group }} mode=0755  
  when: not zabbix_pid_result.stat.exists

- name: install_file | Check zabbix-agent conf directory.
  stat: path={{ zabbix_agent_conf_path }}
  register: zabbix_conf_result  

- name: install_file | Create zabbix conf directory.
  file: path={{ zabbix_agent_conf_path }} state=directory owner={{ zabbix_agent_user }} group={{ zabbix_agent_group }} mode=0755 
  when: not zabbix_conf_result.stat.exists

- name: install_file | Check zabbix-agent logs directory.
  stat: path={{ zabbix_agent_logs_path }}
  register: zabbix_logs_result  

- name: install_file | Create zabbix logs directory.
  file: path={{ zabbix_agent_logs_path }} state=directory owner={{ zabbix_agent_user }} group={{ zabbix_agent_group }} mode=0755
  when: not zabbix_logs_result.stat.exists  

- name: install_file | Configure systemd script.
  template:
    src: zabbix-agent.systemd.j2
    dest: "{%if ansible_distribution|lower == 'centos'%}/usr{% endif %}/lib/systemd/system/zabbix-agent.service"
    mode: 0644