---
# author: fat

software_files_path: "/opt/software"
software_install_path: "/usr/local"

mysql57_version: "5.7.28"

mysql57_file: "mysql-boost-{{ mysql57_version }}.tar.gz"
mysql57_bin_file: "mysql-boost-{{ mysql57_version }}-bin.tar.gz"
mysql57_file_path: "{{ software_files_path }}/{{ mysql57_file }}"
mysql57_file_url: "https://cdn.mysql.com/archives/mysql-5.7/{{ mysql57_file }}"
mysql57_dirname: "mysql-{{ mysql57_version }}"

mysql57_official_glibc: true
mysql57_glibc_file: "mysql-{{ mysql57_version }}-linux-glibc2.12-x86_64.tar.gz"
mysql57_glibc_file_path: "{{ software_files_path }}/{{ mysql57_glibc_file }}"
#mysql57_glibc_file_url: "https://cdn.mysql.com/archives/mysql-5.7/{{ mysql57_glibc_file }}"
mysql57_glibc_dirname: "mysql-{{ mysql57_version }}-linux-glibc2.12-x86_64"

mysql57_port: "3306"
mysql57_user: "root"
mysql57_password: "cmzy2020"
mysql57_datahome: "/mysql_data"
mysql57_basedir: "{{ software_install_path }}/mysql-{{ mysql57_version }}"
mysql57_portdir: "{{ mysql57_datahome }}/{{ mysql57_port }}"
mysql57_datadir: "{{ mysql57_portdir }}/data"
mysql57_cnf : "{{ mysql57_portdir }}/my.cnf"
#mysql57_sock : "{{ mysql57_portdir }}/mysql.sock"
mysql57_sock : "/tmp/mysql.sock"
mysql57_servicename : "mysql{{ mysql57_port }}"
#mysql_sysconfig_dir: "{{ mysql57_portdir }}"
mysql_yum_packages:
   - gcc-c++
   - mysql-libs
   - mysql-devel
   - gcc
   - bison
   - openssl
   - openssl-devel
   - ncurses
   - ncurses-devel
   - make
   - cmake
   - autoconf
   - libaio-devel
   - redhat-lsb-core
   
mysql_apt_packages:
   - gcc
   - libmysql++-dev
   - bison
   - openssl
   - libssl1.0.0
   - libssl-dev
   - libncurses5-dev
   - make
   - cmake
   - autoconf
   - libaio-dev
   - pkg-config
   - lsb-core


mysql57_install_from_source: false
mysql57_source_configure_command: >
  /usr/bin/cmake -DCMAKE_INSTALL_PREFIX={{ mysql57_basedir }}
  -DMYSQL_DATADIR={{ mysql57_datadir }}
  -DMYSQL_TCP_PORT={{ mysql57_port }}
  -DWITH_MYISAM_STORAGE_ENGINE=1
  -DWITH_INNOBASE_STORAGE_ENGINE=1
  -DWITH_ARCHIVE_STORAGE_ENGINE=1
  -DWITH_PARTITION_STORAGE_ENGINE=1
  -DWITH_INNODB_MEMCACHED=1
  -DMYSQL_UNIX_ADDR={{ mysql57_sock }}
  -DWITH_SSL=system
  -DWITH_ZLIB=system
  -DENABLED_LOCAL_INFILE=1
  -DENABLE_DOWNLOADS=1
  -DENABLED_LOCAL_INFILE=1
  -DEXTRA_CHARSETS=all
  -DDEFAULT_CHARSET=utf8mb4
  -DDEFAULT_COLLATION=utf8mb4_general_ci
  -DWITH_BOOST=boost
#  -DSYSCONFDIR={{ mysql_sysconfig_dir }}

mysql57_innodb_buffer_pool_size: "512M"
mysql57_replication_user: {name: 'rep', password: '123456'}
mysql57_replication_master: "127.0.0.1"
mysql57_replication_master_port: "3306"
mysql57_replication_role: ""
mysql57_auto_increment_offset: "1"
mysql57_auto_increment_increment: "1"

mysql57_replication_mode: "gtid"
mysql57_binlog_format: "ROW"

mysql57_replication_channel: {}

mysql57_replication_ga: false
mysql57_replication_ga_first: false
mysql57_replication_ga_single: false
mysql57_group_replication_start_on_boot: "off"
mysql57_group_replication_group_name: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
mysql57_group_recation_local_address: "127.0.0.1:24901"
mysql57_group_replication_group_seeds: "127.0.0.1:24901,127.0.0.1:24902,127.0.0.1:24903"
