---
# author: fat

- name: shutdwon | selinux.
  replace: dest=/etc/selinux/config regexp=^SELINUX=enforcing replace=SELINUX=disabled
  ignore_errors: yes
  tags: selinux
  
- name: Shutdwon selinux.
  shell: setenforce 0
  ignore_errors: true
  tags: selinux

#- name: shutdown | swap.
#  replace: dest=/etc/fstab regexp='(.*)swap(\s+)swap' replace='# \1swap\2swap'
#  tags: swap

- name: shutdwon | services.
  service: name={{ item }} state=stopped enabled=false
  with_items:
    - iptables
    - firewalld
    - ufw
    - NetworkManager
  ignore_errors: yes
  tags:
   - shutdown-fw
