---
# author: fat

- name: env | bashrc.
  blockinfile:
#    path: "{{ __bashrc_file }}"
    path: "/etc/profile"    
    backup: yes
    create: yes
    marker: "# ansible os-init {mark}"
    block: |
      # history actions record，include action time, user, login ip
      HISTFILESIZE=4000
      HISTSIZE=4000
      USER_IP=`who -u am i 2>/dev/null| awk '{print $NF}'|sed -e 's/[()]//g'`
      if [ -z $USER_IP ]
      then
        USER_IP=`hostname`
      fi
      HISTTIMEFORMAT="%F %T $USER_IP:`whoami` "
      export HISTTIMEFORMAT
      # PS1 configure
      PS1="\[\e[37;40m\][\[\e[32;40m\]\u\[\e[37;40m\]@\h \[\e[35;40m\]\W\[\e[0m\]]\\$ "
  tags:
   - bashrc-history-ps1
   
- name: env | bashrc for ubuntu.
  lineinfile:
    path: "/root/.bashrc"    
    backup: yes
    create: yes
    line: PS1="\[\e[37;40m\][\[\e[32;40m\]\u\[\e[37;40m\]@\h \[\e[35;40m\]\W\[\e[0m\]]\\$ "
  when: ansible_os_family == 'Debian'
  tags:
   - bashrc-history-ps1
   


