---
# author: fat

- block:
  - name: upgrade | Update all fractures to the latest version with yum.
    yum:
      name: "*"
      update_only: yes
      state: latest
      exclude: kernel*
    when: "ansible_pkg_mgr == 'yum'"
      
  - name: upgrade | Update all fractures to the latest version with apt.
    apt:
      upgrade: dist
    when: "ansible_pkg_mgr == 'apt'"
  tags:
   - upgrade
